[package]
name = "guessing_game"
version = "0.1.0"
authors = ["David Arinder <david.arinder@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
